# Week 02 Coding: Numpy, Pandas, and MatPlotLib (Lab)

## BEENOS Inc. Machine Learning Study Group

In the second week, you'll practice using `numpy`, `pandas` and `matplotlib`.

In [ ]:
# add 2 to every element of a `list`

mylist = [1, 2, 3, 4, 5]

mylist + 2

But such an operation is trivial for `numpy`:

In [ ]:
# add 2 to every element of an `ndarray`

import numpy as np

myarray = np.array([1,2,3,4,5])

myarray + 2

We can also use `numpy` to create matrices from lists of lists:

In [ ]:
# create a 3x3 matrix from a list of list

morelists = [[1,2,3], [4,5,6], [7,8,9]]

mymatrix = np.array(morelists)

mymatrix

### `numpy` Practice

For the first part of this lab, you'll be completing short exercises to get you used to working with `numpy` arrays.

The exercises are taken from [Machine Learning Plus](https://www.machinelearningplus.com/python/101-numpy-exercises-python/) and increase in difficulty from Level 1 to Level 4.

Feel free to skip around to exercises that challenge you.

Good luck!

**Q.0** Import numpy as `np` and print the version.

*Sample Output*:

> `1.15.4`

In [ ]:
# INSERT CODE HERE

**Q.1** Use `np.array` to create a 1D array of numbers from 0 to 9.

*Output:*

> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# INSERT CODE HERE

**Q.2** Extract all odd numbers from `arr`.

*Output:*

> array([1, 3, 5, 7, 9])

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# INSERT CODE HERE

**Q.3** Use `reshape` to convert a 1D array to a 2D array with two rows.

*Output:*

>     array([[0, 1, 2, 3, 4],
>            [5, 6, 7, 8, 9]])

In [ ]:
arr = np.arange(10)

# INSERT CODE HERE

**Q.4** Use `np.full` to create an nD boolean array. Choose your size and `True` or `False`.

*Sample Output:*

>     array([[ True,  True],
>            [ True,  True],
>            [ True,  True]])

In [ ]:
# INSERT CODE HERE

**Q.5** Use `np.where` to replace all odd numbers in `arr` with `-1`, but **DO NOT** change `arr`.

*Sample Output*:

> array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]) `# newarray`

> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) `# arr`

In [ ]:
arr = np.arange(10)

# INSERT CODE HERE

print(arr, newarray)

**Q.6** Create the following pattern. **Use numpy functions.**

*Output:*

> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
a = np.array([1,2,3])

# INSERT CODE HERE

**Q.7** Get all common items in both `a` and `b`.

*Output:*

> array([2,4])

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# INSERT CODE HERE

**Q.8** Remove from `a` all items in `b`.

*Output:*

> array([0, 1, 2, 4])

In [ ]:
a = np.array([0,1,2,3,4,5])
b = np.array([3,5,6,7,8,9])

# INSERT CODE HERE

**Q.9** Create a 2D array of size 5x3 containing random numbers between 5 and 10.

In [ ]:
# INSERT CODE HERE

**Q.10** Use `np.genfromtxt` to import the Iris flowers dataset from the given url.

*Hint: If your last column shows `nan` values, trying specifying an `object` data type.*

*Output:*

> `# Print the first row`

> array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa']], dtype=object)

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

# INSERT CODE HERE

## Part 1: Pandas

[CHANGE TO PANDAS]
NumPy is short for Numerical Python, and it is the most important package one needs when working with data in Python.

Other popular packages, like `pandas`, depend on the versatile functionality provided by numpy.

The core benefit to using `numpy` is access to its `ndarray` objects.

`ndarray` is short for **n-dimensional arrays**, which allow us to perform vectorized mathematical operations and data manipulation on collections of data.

### `pandas` Practice

For the next part of this lab, you'll be completing short exercises to get you used to working with `numpy` arrays.

The exercises are taken from [Machine Learning Plus](https://www.machinelearningplus.com/python/101-pandas-exercises-python/) and increase in difficulty from Level 1 to Level 3.

Feel free to skip around to exercises that challenge you.

Good luck!

**Q.0** Pandas relies on `numpy`. You should have already imported `numpy`. If not, import it and also import pandas (by convention as `pd`) and check your `pandas` version.

*Sample Output*:

> `0.23.4`

In [ ]:
# INSERT CODE HERE

**Q.1** Like `numpy`, `pandas` has popular structures that it is well known for. The first one is called a **Series**, which is a one-dimensional array. In laymans terms, a Series is simply a *column* of data, like one might find in an Excel spreadsheet.

A Series can hold any data type and can be coerced from multiple data structures. To test this, convert each of the following data structures (a list, an array and a dictionary) into a separate **Series**.

*Sample Output*:

> `# Print the head of the mydict series`

>     a     0
>     b     1
>     c     2
>     d     3
>     e     4
>     dtype: int64

In [ ]:
mylist = list('abcdefghijklmnopqrstuvwyxz')
myarray = np.arange(1, 27)
mydict = dict(zip(mylist,myarray))

mylist_to_series =  # INSERT CODE HERE
myarray_to_series = # INSERT CODE HERE
mydict_to_series =  # INSERT CODE HERE

mydict_to_series.head()

**Q.2** Series can also be coerced into the second fundamental `pandas` data structure, the **DataFrame**. It is a two-dimensional array made up of Series. Again, in laymans terms, a DataFrame is like one spreadsheet in Excel: it contains multiple columns.

Each column of a DataFrame cna hold any data type, and can be created from Series or other data structures. Let's try this by turning your `mydict` series into a `pandas` DataFrame. Use `.reset_index()` to add *both* columns to the table.

*Sample Output*:

> `# Print the head of the dataframe`

>           index  0
>     0     a      0
>     1     b      1
>     2     c      2
>     3     d      3
>     4     e      4

In [ ]:
myseries = pd.Series(mydict)

mydataframe = # INSERT CODE HERE

mydataframe.head()

**Q.3** Our new dataframe looks a bit clunky. One problem is the column names `"index"` and `"0"` don't tell us much about the data in the table.

It might be easier to read if we change those names to `"letter"` and `"position"`, or even `"number"`. You can use `.rename()`.

*Hint: Does your head show `'index'` and `'0'` still? Try using `inplace`!*

*Sample Output*:

> `# Print the head of the dataframe`

>           letter  number
>     0     a       1
>     1     b       2
>     2     c       3
>     3     d       4
>     4     e       5

In [ ]:
#INSERT CODE HERE

mydataframe.head()

**Q.4** Alright, let's practice with a bit of real data. We'll be looking at the [Cars93](https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv) dataset for a few problems.

The dataset has already been loaded for you. Figure out how many rows and columns it contains.

*Sample Output*:

> (93, 27)

In [ ]:
cars_df = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv")

# INSERT CODE HERE

**Q.5** Let's get a bit more info on our dataset. First, we want to figure out the *type* of the data that exists within each column. (What are we working with? Strings? Integers? Floats? Datetime objects?)

This is extremely important to know for manipulating our dataset later, because **all the data in a pandas *Series* or a DataFrame *column* must be the same**.

What types are in the Cars93 dataset?

*Sample Output (first 3 data types)*:

>     Manufacturer    object
>     Model           object
>     Type            object
>     dtype: object

In [ ]:
# INSERT CODE HERE

**Q.6** As you work with real data, you'll soon find out that the more you *know* about the dataset you're working with, the easier it is to build models and make predictions.

One of the things you'll want to know is **summary statistics**: things like mean, standard deviation, maximum and minimum values, etc. Knowing these stats will help you determine whether your data needs to undergo transformation (like scaling and normalization) before modeling.

Show the summary stats for this dataset now. What is each row telling you?

*Sample Output*:

> `# First few columns of the first rows`

>               Min.Price       Price           Max.Price
>     count     86.000000       91.000000       88.000000       ...
>     mean      17.118605       19.616484       21.459091       ...
>     ...

In [ ]:
# INSERT CODE HERE

**Q.7** Let's use our summary statistics to learn more about our data.

Find the `manufacturer`, `model` and `type` of car that has the highest `Price`. Use `.loc[]` to pull out this information.

*Sample Output*:

>               Manufacturer    Model     Type       Price
>     58        Mercedes-Benz   300E      Midsize    61.9

In [ ]:
# INSERT CODE HERE

**Q.8** We want to see if our dataset has any missing values. (If it does, we may need to transform them to make the dataset compatible with machine learning algorithms.)

Find all the missing values in the dataset now.

*Sample Output*:

>               Manufacturer    Model     Type       Price
>     58        Mercedes-Benz   300E      Midsize    61.9

In [ ]:
# INSERT CODE HERE

**Q.9** Normally, we'd need to take a closer look at each column containing `null` values before deciding what to do with them. But for the purpose of this notebook, let's just assume we want to get rid of them!

If you ran the above cell correctly, it should show that the `'Model'` column only has one missing value. We shouldn't miss this one too much. **Drop this row now.** Then, check to see how many missing values are in that column.

*Hint: If your code still shows 1 missing value in `'Model'`, try using `inplace`!*

*Output:*

> `# Shape of the dataframe with the missing value 'Model' row gone`

> (92, 27)

In [ ]:
# drop the row with a missing value in `Model`

# INSERT CODE HERE

# check the shape of the dataframe; there should be 92 rows
cars_df.shape

In [ ]:
# check that the missing value from `Model` was removed

# INSERT CODE HERE

**Q.10** We can drop entire rows as well. Again, in real life we'd want to investigate before doing this. But this is just for practice! So let's try it out.

If you ran the Q.8 code cell correctly, you should see that the column `'Luggage.room'` has 19 missing values. That's way more than any other column of the dataset!

Get rid of this column now.

*Output:*

> `# Shape of the dataframe with "Luggage.room" gone`

> (92, 26)

In [ ]:
# INSERT CODE HERE

**Q.11** Instead of dropping null values, what if we wanted to replace them instead? Called *imputation*, this can be a useful solution if we don't want to drop null observations, or if doing so would reduce our dataset by a significant size.

Let's practice simple mean imputation next. Replace the missing values in the `Min.Price` and `Max.Price` columns with their respective means.

*Hint: What output did `.describe()` return to you?*

*Output:*

> `> cars_df['Min.Price'].isna().any()`

> False

In [ ]:
# check that there are null values; should return `True`

cars_df[['Min.Price', 'Max.Price']].isna().any()

In [ ]:
# INSERT CODE HERE

In [ ]:
# check that all null values have been removed; should return `False`

cars_df[['Min.Price', 'Max.Price']].isna().any()

**Q.12** Another transformation we might want to perform is **standardization.** This means that all values are **normalized** to have a mean of 0 and a standard deviation of 1, and **scaled** to be in the inclusive range of 0 to 1.

Don't worry too much about why we need to do this yet! It will help us build better predictive models in the future.

For now, try to standardize the values of any numeric column in the Cars93 dataframe. The numeric columns have been pulled out for you and saved as `numeric_cars_df`.

1. **First, fill any missing values with the column mean.**
2. **Then, normalize all columns in the dataframe.**
3. **Finally, scale all values to be between 0 and 1.**

*Hint: You can normalize data by subtracting the mean and dividing by the standard deviation.*

*You can scale the data by subtracting it from the max, and dividing by the range `max - min`.*

*Sample Output:*

> `# First few columns of the first few rows`

>           Min.Price   Price      Max.Price
>     0     0.84        0.84       0.85       ...
>     1     0.42        0.51       0.57       ...
>     ...

In [ ]:
# pull out only numeric columns of the dataframe and check that they are not standardized
numeric_cars_df = cars_df[list(cars_df.mean().keys())]

numeric_cars_df.head()

In [ ]:
# fill in all missing values with the column mean

# INSERT CODE HERE

In [ ]:
# normalize the data (subtract the mean and divide by the standard deviation)

# INSERT CODE HERE

In [ ]:
# scale the data between 0 and 1 (subtract it from the max, and divide by the range)

# INSERT CODE HERE

# check that the data is now standardized
numeric_cars_df.head()

**Q.13** One last thing we'll look at is text in dataframes. Frequently, our data will be unstructured, and we'll have to do a bit of cleaning up before we could use it.

We've already seen how to transform numeric data (by scaling, normalizing, and imputing or dropping missing values). Now, let's take a quick look at how to deal with textual data.

If your data comes in one long string, you might want to split it up across different columns and work with each piece separately. For this exercise, we'll take a column full of strings and split it up into three columns.

*Output:*

>           No.     Name         Kanji
>     0     01      Chiyoda      千代田区
>     1     03      Minato       港区
>     2     04      Shinjuku     新宿区
>     3     09      Shinagawa    品川区

In [ ]:
# create and view the dataframe
string_dataframe = pd.DataFrame(["No., Name    Kanji",
"01, Chiyoda    千代田区",
"03, Minato    港区",
"04, Shinjuku    新宿区",
"09, Shinagawa    品川区"], columns=['row'])

string_dataframe

In [ ]:
# split the text in each row into 3 new columns

# INSERT CODE HERE

In [ ]:
# if necessary, rename the columns and reset the index

# INSERT CODE HERE

# view the final dataframe

string_dataframe

## Part 4: Matplotlib

[intro to what matplotlib is, and why we use it]

[what they'll be doing in this section]

- draw simple plot
- create multiple subplots
- piechart
- histogram
- bar plot
- saving a plot

https://jakevdp.github.io/PythonDataScienceHandbook/04.00-introduction-to-matplotlib.html

https://heartbeat.fritz.ai/introduction-to-matplotlib-data-visualization-in-python-d9143287ae39

https://www.tutorialdocs.com/article/python-matplotlib-tutorial.html

EXERCISES: https://www.w3resource.com/graphics/matplotlib/